name: EasyBackUp
version: 1.3.0
main: io.github.wzqLovesPizza.easybackup.EasyBackUp
api-version: 1.20
commands:
  ebu:
    description: EasyBackUp 主命令
    usage: |
      /ebu now                # 立即备份
      /ebu status             # 查看上次/下次备份状态
      /ebu reload             # 热重载配置
      /ebu set <key> <value>  # 动态修改常用配置（例如 interval, output-dir）
    permission: ebu.use
permissions:
  ebu.use:
    description: 允许使用 /ebu 主命令
    default: op
  ebu.now:
    description: 允许立刻备份
    default: op
  ebu.status:
    description: 允许查看备份状态
    default: op
  ebu.reload:
    description: 允许热重载配置
    default: op
  ebu.set:
    description: 允许修改常用配置
    default: op